<a href="https://colab.research.google.com/github/number1coder01/Machine-Learning/blob/main/Lecture27OneHotEncoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('cars.csv')

In [4]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [5]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [6]:
# 1.OneHotEncoding using Pandas

In [33]:
new_df = pd.get_dummies(df,columns=['fuel','owner']) # unn cols ka list jisme one-hot lagana

In [34]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8128 entries, 0 to 8127
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   brand                       8128 non-null   object
 1   km_driven                   8128 non-null   int64
 2   selling_price               8128 non-null   int64
 3   fuel_CNG                    8128 non-null   bool
 4   fuel_Diesel                 8128 non-null   bool
 5   fuel_LPG                    8128 non-null   bool
 6   fuel_Petrol                 8128 non-null   bool
 7   owner_First Owner           8128 non-null   bool
 8   owner_Fourth & Above Owner  8128 non-null   bool
 9   owner_Second Owner          8128 non-null   bool
 10  owner_Test Drive Car        8128 non-null   bool
 11  owner_Third Owner           8128 non-null   bool
dtypes: bool(9), int64(2), object(1)
memory usage: 262.1+ KB

In [24]:
#2. K-1 OneHotEncoding : to solve the Dummy Variable Trap(Multicollinearity)

In [31]:
new_df = pd.get_dummies(df,columns=['fuel','owner'],drop_first=True)

In [32]:
new_df.info() #pehla column hat gaya

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8128 entries, 0 to 8127
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   brand                       8128 non-null   object
 1   km_driven                   8128 non-null   int64
 2   selling_price               8128 non-null   int64
 3   fuel_Diesel                 8128 non-null   bool
 4   fuel_LPG                    8128 non-null   bool
 5   fuel_Petrol                 8128 non-null   bool
 6   owner_Fourth & Above Owner  8128 non-null   bool
 7   owner_Second Owner          8128 non-null   bool
 8   owner_Test Drive Car        8128 non-null   bool
 9   owner_Third Owner           8128 non-null   bool
dtypes: bool(7), int64(2), object(1)
memory usage: 246.2+ KB

In [13]:
#3. OneHotEncoding using Sklearn -> yeh better rehta hai than pandas ka ohe

In [35]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:4],df.iloc[:,-1],test_size=0.2,random_state=2)

In [37]:
X_train.head()

         brand  km_driven    fuel         owner
5571   Hyundai      35000  Diesel   First Owner
2038      Jeep      60000  Diesel   First Owner
2957   Hyundai      25000  Petrol   First Owner
7618  Mahindra     130000  Diesel  Second Owner
6684   Hyundai     155000  Diesel   First Owner

In [38]:
from sklearn.preprocessing import OneHotEncoder

In [55]:
# drop first h isliye 9 ki jagah 7 hi aayenge
ohe = OneHotEncoder(drop='first', sparse_output=False, dtype=np.int32)

In [56]:
# yeh ohe ek sparse matrix produce karega jisme no. cols = categories jitni di hai
# but since sparse = false toh yeh o/p will be a numpy array
X_train_new = ohe.fit_transform(X_train[['fuel','owner']])

In [42]:
X_test_new = ohe.transform(X_test[['fuel','owner']])

In [57]:
# yaha 7 hai kyuki isme brand aur km_driven wala feature nahi h
X_train_new.shape

(6502, 7)

In [58]:
# appending the new_X_Train into the brand and km_driven wala array
np.hstack((X_train[['brand','km_driven']].values,X_train_new))

array([['Hyundai', 35000, 1, ..., 0, 0, 0],
       ['Jeep', 60000, 1, ..., 0, 0, 0],
       ['Hyundai', 25000, 0, ..., 0, 0, 0],
       ...,
       ['Tata', 15000, 0, ..., 0, 0, 0],
       ['Maruti', 32500, 1, ..., 1, 0, 0],
       ['Isuzu', 121000, 1, ..., 0, 0, 0]], dtype=object)

In [59]:
# 4.OneHotEncoding with Top Categories (Jisme categories bhot saari hain)

In [60]:
counts = df['brand'].value_counts()

In [61]:
df['brand'].nunique()
threshold = 100

In [62]:
repl = counts[counts <= threshold].index

In [63]:
pd.get_dummies(df['brand'].replace(repl, 'uncommon')).sample(5)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
5992,False,False,False,False,False,False,True,False,False,False,False,False,False
155,False,False,False,False,False,False,False,False,True,False,False,False,False
5724,False,False,True,False,False,False,False,False,False,False,False,False,False
3704,False,False,False,False,True,False,False,False,False,False,False,False,False
5388,False,False,False,False,True,False,False,False,False,False,False,False,False