<a href="https://colab.research.google.com/github/number1coder01/Machine-Learning/blob/main/Lecture26EncodingCategoricalData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
import numpy as np
import pandas as pd

In [29]:
df = pd.read_csv('customer.csv')
df.sample(5)

    age  gender   review education purchased
45   61    Male     Poor        PG       Yes
21   32    Male  Average        PG        No
8    65  Female  Average        UG        No
44   77  Female  Average        UG        No
0    30  Female  Average    School        No

In [30]:
df = df.iloc[:,2:]
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [31]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 0:2], df.iloc[:, -1], test_size=0.2)

In [32]:
from sklearn.preprocessing import OrdinalEncoder

In [33]:
X_train

     review education
29  Average        UG
23     Good    School
22     Poor        PG
14     Poor        PG
30  Average        UG
6      Good    School
21  Average        PG
24  Average        PG
35     Poor    School
17     Poor        UG
36     Good        UG
11     Good        UG
10     Good        UG
41     Good        PG
4   Average        UG
3      Good        PG
31     Poor    School
28     Poor    School
43     Poor        PG
25     Good    School
49     Good        UG
42     Good        PG
9      Good        UG
19     Poor        PG
33     Good        PG
16     Poor        UG
32  Average        UG
48     Good        UG
27     Poor        PG
39     Poor        PG
40     Good    School
15     Poor        UG
37  Average        PG
13  Average    School
45     Poor        PG
7      Poor    School
1      Poor        UG
26     Poor        PG
20  Average    School
5   Average    School

In [34]:
# iss obj ko we give a list of list of categories -> jitne categorical data ko transform karna utne items iss list mei aayenge
# also ensure that u pass in order of lowest to highest order in this list
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [35]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [36]:
X_train = oe.transform(X_train)
X_test = oe.transform(X_test)

In [14]:
X_train # now ab according to the input categories ur data will be numericalised

array([[1., 1.],
       [1., 1.],
       [2., 2.],
       [2., 0.],
       [2., 1.],
       [1., 2.],
       [2., 1.],
       [0., 2.],
       [2., 0.],
       [0., 0.],
       [0., 2.],
       [1., 1.],
       [2., 2.],
       [1., 1.],
       [0., 1.],
       [2., 0.],
       [1., 0.],
       [0., 0.],
       [0., 1.],
       [1., 2.],
       [2., 1.],
       [2., 0.],
       [1., 1.],
       [2., 2.],
       [0., 0.],
       [0., 2.],
       [0., 2.],
       [2., 1.],
       [0., 2.],
       [2., 2.],
       [1., 0.],
       [1., 1.],
       [0., 2.],
       [0., 2.],
       [1., 0.],
       [1., 2.],
       [0., 0.],
       [0., 1.],
       [2., 2.],
       [2., 0.]])

In [37]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [38]:
from sklearn.preprocessing import LabelEncoder

In [39]:
le = LabelEncoder() # yaha par order nahi decide kar skte aap -> it is randomly decided
le.fit(y_train)

LabelEncoder()

In [40]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [41]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [42]:
y_train

array([1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1])